# Generated by Django 2.1.1 on 2018-09-23 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180922_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_img',
            field=models.CharField(default='', max_length=255),
        ),
    ]
