# Generated by Django 2.1.1 on 2018-09-23 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_category_cat_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='group_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Group'),
            preserve_default=False,
        ),
    ]
