# Generated by Django 2.1.1 on 2018-09-25 00:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20180924_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(default='', related_name='group_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
