# Generated by Django 2.1.1 on 2018-09-25 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20180924_1900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='admin_id',
            new_name='group_creator',
        ),
    ]
