# Generated by Django 2.1.1 on 2018-09-26 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20180925_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='event',
            name='event_img',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='group',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_group', to='api.Category'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
