# Generated by Django 2.0.4 on 2018-09-30 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_group_group_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_events', to='api.Group'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizer_name', to=settings.AUTH_USER_MODEL),
        ),
    ]
