# Generated by Django 2.0.4 on 2018-10-02 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_event_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='hometown',
            field=models.CharField(default='', max_length=255),
        ),
    ]
