# Generated by Django 2.0.4 on 2018-10-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20181002_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(default='Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Euismod lacinia at quis risus sed vulputate odio. Vulputate eu scelerisque felis imperdiet proin. Egestas egestas fringilla phasellus faucibus scelerisque eleifend. Imperdiet proin fermentum leo vel. Gravida quis blandit turpis cursus in hac. Egestas sed tempus urna et. Eget egestas purus viverra accumsan in nisl. Nec sagittis aliquam malesuada bibendum arcu. Facilisi etiam dignissim diam quis. Hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper. Nisl vel pretium lectus quam id leo in vitae turpis. Donec adipiscing tristique risus nec feugiat. Elementum facilisis leo vel fringilla est ullamcorper eget nulla facilisi. Accumsan tortor posuere ac ut.'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_img',
            field=models.TextField(default='https://images.pexels.com/photos/136931/pexels-photo-136931.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=350'),
        ),
    ]
